version: '3'

services:
  nsqlookupd:
    image: nsqio/nsq:latest
    command: /nsqlookupd
    ports:
      - "4160:4160"  # HTTP interface
      - "4161:4161"  # TCP interface
    volumes:
      - nsq_data:/data

  nsqd:
    image: nsqio/nsq:latest
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4161
    ports:
      - "4150:4150"  # HTTP interface
      - "4151:4151"  # TCP interface
      - "4152:4152"  # HTTP interface for /stats
    volumes:
      - nsq_data:/data
    depends_on:
      - nsqlookupd

  topic-creator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nsqd

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - nsqd

volumes:
  nsq_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data