version: '3.8'
services:
  topic-master:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: topic-master:latest
    container_name: topic-master
    command:
      - /app/topic-master
      - -data_path=/app/infra/data/
      - -port=4181
      - -nsqlookupd_http_address=http://localhost:4161
    environment:
      - TOPIC_MASTER_ROOT_PASS=rootroot
    depends_on:
      - nsqlookupd
  test-script:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-script:latest
    container_name: test-script
    depends_on:
      - topic-master
